/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `/welcome`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/caja/cuentas`; params?: Router.UnknownInputParams; } | { pathname: `/caja/logout`; params?: Router.UnknownInputParams; } | { pathname: `/caja/menu`; params?: Router.UnknownInputParams; } | { pathname: `/Cliente/carrito`; params?: Router.UnknownInputParams; } | { pathname: `/Cliente/cliente`; params?: Router.UnknownInputParams; } | { pathname: `/Cliente/logout`; params?: Router.UnknownInputParams; } | { pathname: `/Cliente/pedidoStatus`; params?: Router.UnknownInputParams; } | { pathname: `/Cliente/QRScanner`; params?: Router.UnknownInputParams; } | { pathname: `/cocinero/logout`; params?: Router.UnknownInputParams; } | { pathname: `/cocinero/pedidos`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/register`; params?: Router.UnknownOutputParams; } | { pathname: `/welcome`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/caja/cuentas`; params?: Router.UnknownOutputParams; } | { pathname: `/caja/logout`; params?: Router.UnknownOutputParams; } | { pathname: `/caja/menu`; params?: Router.UnknownOutputParams; } | { pathname: `/Cliente/carrito`; params?: Router.UnknownOutputParams; } | { pathname: `/Cliente/cliente`; params?: Router.UnknownOutputParams; } | { pathname: `/Cliente/logout`; params?: Router.UnknownOutputParams; } | { pathname: `/Cliente/pedidoStatus`; params?: Router.UnknownOutputParams; } | { pathname: `/Cliente/QRScanner`; params?: Router.UnknownOutputParams; } | { pathname: `/cocinero/logout`; params?: Router.UnknownOutputParams; } | { pathname: `/cocinero/pedidos`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `/welcome${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/caja/cuentas${`?${string}` | `#${string}` | ''}` | `/caja/logout${`?${string}` | `#${string}` | ''}` | `/caja/menu${`?${string}` | `#${string}` | ''}` | `/Cliente/carrito${`?${string}` | `#${string}` | ''}` | `/Cliente/cliente${`?${string}` | `#${string}` | ''}` | `/Cliente/logout${`?${string}` | `#${string}` | ''}` | `/Cliente/pedidoStatus${`?${string}` | `#${string}` | ''}` | `/Cliente/QRScanner${`?${string}` | `#${string}` | ''}` | `/cocinero/logout${`?${string}` | `#${string}` | ''}` | `/cocinero/pedidos${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `/welcome`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/caja/cuentas`; params?: Router.UnknownInputParams; } | { pathname: `/caja/logout`; params?: Router.UnknownInputParams; } | { pathname: `/caja/menu`; params?: Router.UnknownInputParams; } | { pathname: `/Cliente/carrito`; params?: Router.UnknownInputParams; } | { pathname: `/Cliente/cliente`; params?: Router.UnknownInputParams; } | { pathname: `/Cliente/logout`; params?: Router.UnknownInputParams; } | { pathname: `/Cliente/pedidoStatus`; params?: Router.UnknownInputParams; } | { pathname: `/Cliente/QRScanner`; params?: Router.UnknownInputParams; } | { pathname: `/cocinero/logout`; params?: Router.UnknownInputParams; } | { pathname: `/cocinero/pedidos`; params?: Router.UnknownInputParams; };
    }
  }
}
